# Generated by Django 2.2 on 2021-02-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20210130_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tag',
            field=models.ManyToManyField(null=True, related_name='recipe_tag', to='recipes.Tag'),
        ),
    ]
